llm:
  model_name: "gpt-4"
  temperature: 0.7
  max_tokens: 2048
  api_key_env: "OPENAI_API_KEY"

code_encoder:
  model_name: "microsoft/graphcodebert-base"
  max_length: 512
  embedding_dim: 768

rl_agent:
  algorithm: "PPO"
  learning_rate: 0.0003
  gamma: 0.99
  n_steps: 2048
  batch_size: 64

fuzzy_logic:
  threshold_delta: 0.5
  confidence_threshold: 0.7
  semantic_similarity_model: "sentence-transformers/all-MiniLM-L6-v2"

knowledge_graph:
  neo4j_uri: "bolt://localhost:7687"
  neo4j_user: "neo4j"
  neo4j_password: "testagent123"
